name: Terraform PROD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    name: Terraform Plan PROD
    runs-on: ubuntu-latest

    env:
      TF_WORKING_DIR: environments/prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP using WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-terraform-sa@PROJECT_ID.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan -out=tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod-tfplan
          path: ${{ env.TF_WORKING_DIR }}/tfplan

  terraform-apply:
    name: Terraform Apply PROD
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: prod   # ðŸ”¥ Requires GitHub environment approval

    env:
      TF_WORKING_DIR: environments/prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: prod-tfplan
          path: ${{ env.TF_WORKING_DIR }}

      - name: Authenticate to GCP using WIF
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/PROJECT_NUMBER/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "github-terraform-sa@PROJECT_ID.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}