name: sit Terraform Deploy

on:
  push:
    branches:
      - sit

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: sit-project-id
      REGION: us-central1

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate to GCP using WIF
        uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: ${{ secrets.WIF_PROVIDER_sit }}
          service_account: ${{ secrets.SA_EMAIL_sit }}

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: |
          cd environments/sit
          terraform init

      - name: Terraform Validate
        run: |
          cd environments/sit
          terraform validate

      - name: Terraform Plan
        run: |
          cd environments/sit
          terraform plan

      - name: Terraform Apply
        run: |
          cd environments/sit
          terraform apply -auto-approve